---

title: '[ANNOUNCEMENT] - '
labels: ["announcement 🥳"]
body:
  - type: markdown
    attributes:
      value: Discussion Category form for Announcements.

  - type: dropdown
    id: type
    attributes:
      label: Type of Announcement
      multiple: false
      options:
        - 'New version'
        - 'New feature'
        - 'Breaking changes'
        - 'Comunity'
        - 'Other'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detail description of an announcement.
    validations:
      required: false
